#pragma once
#include <windows.h>
#include <Winternl.h>   
#include <iostream>
#include <intrin.h>
using namespace std;  //ÃüÃû¿Õ¼ä


namespace REFLECTIVELOADER
{
	typedef HMODULE(WINAPI* LPFN_LOADLIBRARYA) (_In_ LPCSTR);
	typedef LPVOID(WINAPI* LPFN_GETPROCADDRESS) (HMODULE, LPCSTR);
	typedef LPVOID(WINAPI* LPFN_VIRTUALALLOC) (LPVOID, SIZE_T, DWORD, DWORD);
	typedef VOID(WINAPI* LPFN_EXITTHREAD) (DWORD);
	typedef NTSTATUS(NTAPI* LPFN_NTFLUSHINSTRUCTIONCACHE) (HANDLE, PVOID, ULONG);
	typedef BOOL(WINAPI* LPFN_DLLMAIN)(HINSTANCE, DWORD, LPVOID);
	typedef BOOL(WINAPI* LPFN_MYFUNCTION)(LPVOID, DWORD);
}

#define DEREFERENCE(Value) *(UINT_PTR *)(Value)
#define DEREFERENCE_64(Value) *(DWORD64 *)(Value)
#define DEREFERENCE_32(Value) *(DWORD *)(Value)
#define DEREFERENCE_16(Value) *(WORD *)(Value)
#define DEREFERENCE_8 (Value) *(BYTE *)(Value)

#define KERNEL32DLL_HASH				0x6A4ABC5B
#define NTDLLDLL_HASH					0x3CFA685D

#define LOADLIBRARYA_HASH				0xEC0E4E8E
#define GETPROCADDRESS_HASH				0x7C0DFCAA
#define VIRTUALALLOC_HASH				0x91AFCA54
#define EXITTHREAD_HSAH					0x60E0CEEF
#define NTFLUSHINSTRUCTIONCACHE_HASH	0x534C0AB8
#define RTLEXITUSERTHREAD_HASH			0xFF7F061A 

typedef struct
{
	WORD	Offset : 12;
	WORD	Type : 4;
}IMAGE_BASE_RELOCATION_ITEM, * PIMAGE_BASE_RELOCATION_ITEM;
